# Build Stage
FROM node:20-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

# Declare build-time args (passed via docker-compose build.args)
# Vite bakes these into the JS bundle during `npm run build`
ARG VITE_SPECKLE_SERVER
ARG VITE_SPECKLE_TOKEN
ARG VITE_NORMALIZER_URL=/normalizer
ARG VITE_OPENAI_API_KEY
ARG VITE_OLLAMA_BASE_URL
ARG VITE_OLLAMA_MODEL=llama3
ARG VITE_LMSTUDIO_BASE_URL
ARG VITE_LMSTUDIO_MODEL=local-model
ARG VITE_MISTRAL_API_KEY
ARG VITE_EXTRA_SPECKLE_SERVERS
ARG VITE_BCF_URL=/bcf
ARG VITE_BCF_API_KEY

ENV VITE_SPECKLE_SERVER=$VITE_SPECKLE_SERVER
ENV VITE_SPECKLE_TOKEN=$VITE_SPECKLE_TOKEN
ENV VITE_NORMALIZER_URL=$VITE_NORMALIZER_URL
ENV VITE_OPENAI_API_KEY=$VITE_OPENAI_API_KEY
ENV VITE_OLLAMA_BASE_URL=$VITE_OLLAMA_BASE_URL
ENV VITE_OLLAMA_MODEL=$VITE_OLLAMA_MODEL
ENV VITE_LMSTUDIO_BASE_URL=$VITE_LMSTUDIO_BASE_URL
ENV VITE_LMSTUDIO_MODEL=$VITE_LMSTUDIO_MODEL
ENV VITE_MISTRAL_API_KEY=$VITE_MISTRAL_API_KEY
ENV VITE_EXTRA_SPECKLE_SERVERS=$VITE_EXTRA_SPECKLE_SERVERS
ENV VITE_BCF_URL=$VITE_BCF_URL
ENV VITE_BCF_API_KEY=$VITE_BCF_API_KEY

COPY . .
RUN npm run build

# Production Stage
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf.template /etc/nginx/templates/default.conf.template

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
